import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ConvexClientProvider from '@/components/ConvexClientProvider'
import { Sidebar } from '@/components/Sidebar'
import { UserButton } from '@clerk/nextjs'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ConvexClientProvider>
            <SignedIn>
              <div className="flex h-screen bg-background">
                <Sidebar />
                <div className="flex-1 flex flex-col">
                  <header className="border-b p-4 flex justify-between items-center">
                    <h1 className="text-xl font-semibold">T3 Chat</h1>
                    <UserButton afterSignOutUrl="/" />
                  </header>
                  <main className="flex-1 overflow-hidden">
                    {children}
                  </main>
                </div>
              </div>
            </SignedIn>
            <SignedOut>
              {children}
            </SignedOut>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}